services:
  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  rails:
    build:
      context: .
    container_name: rails_app
    environment:
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: project_manager_development
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    depends_on:
      - db