default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: mario
  password: 123mudar
  port: <%= ENV.fetch('POSTGRES_PORT') {'5432'} %>

development:
  <<: *default
  database: project_manager_development

test:
  <<: *default
  database: project_manager_test

production:
  <<: *default
  database: project_manager_production

homolog:
  <<: *default
  database: project_manager_homolog
